backend:
  name: git-gateway
  branch: main # Branch to update (master or main)

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Slug must contain only lowercase letters, numbers, and hyphens']}
      - {label: "Publish Date", name: "publishedAt", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Category", name: "category", widget: "select", options: ["Hiring Strategy", "Remote Work", "AI & Technology", "Diversity & Inclusion", "Interview Process", "Startup Hiring"]}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Read Time", name: "readTime", widget: "string", hint: "e.g., 5 min read"}
      - label: "Author"
        name: "author"
        widget: "object"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Role", name: "role", widget: "string"}
          - {label: "Avatar", name: "avatar", widget: "image"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Meta Title", name: "metaTitle", widget: "string"}
          - {label: "Meta Description", name: "metaDescription", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}